import { StrictMode, useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { api } from './api';
import type { AdminDashboard, Appointment, Availability, Catalog, DirectoryProfessional, DirectoryUser, ProfessionalAppointment, ProfessionalSpecialty, Registration, Session, Specialty } from './api';
import clinicalBanner from './assets/clinical-excellence-banner.png';
import './styles.css';

const IDLE_TIMEOUT_MS = 10 * 60 * 1000;
const SERVER_TOUCH_INTERVAL_MS = 60 * 1000;
const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
const empty: Registration = { firstName: '', lastName: '', documentType: 'CC', documentNumber: '', email: '', phone: '', password: '' };
const format = (value: string) => new Date(value).toLocaleString('es-CO', { dateStyle: 'medium', timeStyle: 'short' });

function Access({ onSession, expired }: { onSession: (session: Session) => void; expired: boolean }) {
  const [signup, setSignup] = useState(false);
  const [values, setValues] = useState(empty);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const field = (key: keyof Registration) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setValues(current => ({ ...current, [key]: event.target.value }));
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setMessage('');
    try {
      if (signup) { await api.register(values); setSignup(false); setValues(empty); setMessage('Cuenta creada. Ahora puedes iniciar sesión.'); }
      else onSession(await api.login(values.email, values.password));
    } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible continuar.'); }
    finally { setBusy(false); }
  }
  return <main className="access"><section className="hero"><p className="eyebrow">ATENCIÓN DIGITAL</p><h1>Agenda Salud</h1><p>Tu cuidado, organizado alrededor de tu tiempo.</p><div className="hero-pulse"><span />Disponibilidad y seguimiento en un solo lugar</div></section><form className="card access-card" onSubmit={submit}><h2>{signup ? 'Crear cuenta' : 'Bienvenido de nuevo'}</h2><p className="muted">{signup ? 'Crea un acceso seguro para gestionar tus citas.' : 'Ingresa para revisar tu agenda y próximos pasos.'}</p>{expired && <p className="message" role="alert">Tu sesión se cerró por 10 minutos sin interacción. Inicia sesión nuevamente.</p>}{message && <p className="message" role="alert">{message}</p>}{signup && <div className="form-grid"><label>Nombres<input required value={values.firstName} onChange={field('firstName')} /></label><label>Apellidos<input required value={values.lastName} onChange={field('lastName')} /></label><label>Tipo<select value={values.documentType} onChange={field('documentType')}><option>CC</option><option>CE</option><option>TI</option><option>PA</option><option>PPT</option></select></label><label>Documento<input required value={values.documentNumber} onChange={field('documentNumber')} /></label><label>Teléfono<input required value={values.phone} onChange={field('phone')} /></label></div>}<label>Correo<input required type="email" value={values.email} onChange={field('email')} /></label><label>Contraseña<input required type="password" minLength={8} value={values.password} onChange={field('password')} /></label><button disabled={busy}>{busy ? 'Procesando…' : signup ? 'Crear cuenta' : 'Iniciar sesión'}</button><button className="link" type="button" onClick={() => setSignup(!signup)}>{signup ? 'Volver al inicio de sesión' : 'Crear cuenta'}</button></form></main>;
}

function Booking({ session }: { session: Session }) {
  const [locations, setLocations] = useState<Catalog[]>([]); const [specialties, setSpecialties] = useState<Specialty[]>([]); const [location, setLocation] = useState(''); const [specialty, setSpecialty] = useState(''); const [date, setDate] = useState(tomorrow); const [slots, setSlots] = useState<Availability[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { void Promise.all([api.locations(), api.specialties()]).then(([a, b]) => { setLocations(a); setSpecialties(b); setLocation(String(a[0]?.id || '')); setSpecialty(String(b[0]?.id || '')); }).catch(error => setNotice(error.message)); }, []);
  async function search(event: FormEvent) { event.preventDefault(); try { const found = await api.availability(+location, +specialty, date); setSlots(found); setNotice(`${found.length} alternativas encontradas.`); } catch (error) { setNotice(error instanceof Error ? error.message : 'Error'); } }
  return <section className="page-section"><div className="section-title"><div><p className="eyebrow">NUEVA CITA</p><h2>Encuentra el mejor horario</h2></div><span className="tag">Paso 1 de 2</span></div><form className="filters elevated" onSubmit={search}><label>Sede<select value={location} onChange={e => setLocation(e.target.value)}>{locations.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Especialidad<select value={specialty} onChange={e => setSpecialty(e.target.value)}>{specialties.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Fecha<input type="date" min={tomorrow} value={date} onChange={e => setDate(e.target.value)} /></label><button>Ver horarios</button></form>{notice && <p className="message">{notice}</p>}<div className="slot-grid">{slots.map(slot => <article className="slot" key={`${slot.professionalId}-${slot.startAt}`}><div className="avatar">{slot.firstName[0]}{slot.lastName[0]}</div><strong>{slot.firstName} {slot.lastName}</strong><span>{format(slot.startAt)}</span><small>{slot.durationMinutes} minutos</small><button onClick={() => void api.book(session.accessToken, { professionalId: slot.professionalId, locationId: +location, specialtyId: +specialty, startAt: slot.startAt }).then(() => setNotice('Cita registrada correctamente.')).catch(error => setNotice(error.message))}>Elegir horario</button></article>)}</div></section>;
}

function MyAppointments({ session }: { session: Session }) {
  const [items, setItems] = useState<Appointment[]>([]); const [notice, setNotice] = useState(''); const load = () => api.appointments(session.accessToken).then(setItems).catch(error => setNotice(error.message));
  useEffect(() => { void load(); }, []);
  return <section className="page-section"><div className="section-title"><div><p className="eyebrow">SEGUIMIENTO</p><h2>Mis citas</h2></div><span className="tag">{items.length} registradas</span></div>{notice && <p className="message">{notice}</p>}<div className="timeline">{items.map(item => <article className="appointment-card" key={item.id}><div className="status-dot" /><div><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span><h3>{item.specialty}</h3><p>{item.location} · {item.professionalCode}</p><strong>{format(item.scheduledStartAt)}</strong></div>{item.status === 'APPROVED' && <div className="actions"><button onClick={() => void api.cancel(session.accessToken, item.id).then(load).catch(error => setNotice(error.message))}>Cancelar</button><button className="secondary" onClick={() => { const startAt = window.prompt('Nueva fecha y hora (YYYY-MM-DDTHH:mm)'); if (startAt) void api.reschedule(session.accessToken, item.id, startAt).then(() => setNotice('Solicitud enviada.')).catch(error => setNotice(error.message)); }}>Reprogramar</button></div>}</article>)}</div></section>;
}

function Professional({ session }: { session: Session }) {
  const [items, setItems] = useState<ProfessionalAppointment[]>([]); const [specialties, setSpecialties] = useState<ProfessionalSpecialty[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { void Promise.all([api.agenda(session.accessToken, tomorrow, tomorrow), api.professionalSpecialties(session.accessToken)]).then(([agenda, assigned]) => { setItems(agenda); setSpecialties(assigned); }).catch(error => setNotice(error instanceof Error ? error.message : 'No fue posible cargar la información clínica.')); }, [session.accessToken]);
  return <section className="page-section"><section className="professional-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(20,24,30,.88),rgba(20,24,30,.18)),url(${clinicalBanner})` }}><div><p className="eyebrow light">ESTÁNDARES DE ATENCIÓN</p><h2>Tu agenda, con visión clínica global.</h2><p>Información relevante para cada especialidad que atiendes.</p></div></section><div className="section-title"><div><p className="eyebrow">OPERACIÓN CLÍNICA</p><h2>Agenda de mañana</h2></div><span className="tag">{items.length} atenciones</span></div>{notice && <p className="message" role="alert">{notice}</p>}<div className="metric-row"><article><strong>{items.length}</strong><span>Citas aprobadas</span></article><article><strong>{items.filter(item => item.status === 'APPROVED').length}</strong><span>Por cerrar</span></article><article><strong>{specialties.length}</strong><span>Especialidades asignadas</span></article></div><section className="specialty-insights" aria-labelledby="specialty-insights-title"><div className="section-title"><div><p className="eyebrow">ACTUALIZACIÓN CIENTÍFICA</p><h3 id="specialty-insights-title">Mis especialidades</h3></div><span className="tag">Fuente: PubMed</span></div>{specialties.length === 0 ? <p className="muted">Aún no tienes especialidades activas asignadas.</p> : <div className="insight-grid">{specialties.map(item => <article className="insight-card" key={item.id}><div><span className="specialty-label">{item.primarySpecialty ? 'Especialidad principal' : 'Especialidad'}</span><h4>{item.name}</h4></div>{item.latestArticle.available ? <><p className="article-title">{item.latestArticle.title}</p><p className="article-meta">{item.latestArticle.journal}{item.latestArticle.publishedAt ? ` · ${item.latestArticle.publishedAt}` : ''}{item.latestArticle.firstAuthor ? ` · ${item.latestArticle.firstAuthor}` : ''}</p><a href={item.latestArticle.url} target="_blank" rel="noreferrer">Ver publicación ↗</a></> : <p className="muted">No fue posible consultar PubMed ahora. Intenta actualizar más tarde.</p>}</article>)}</div>}</section><div className="agenda-list">{items.map(item => <article className="appointment-card" key={item.id}><div className="time-block">{new Date(item.scheduledStartAt).toLocaleTimeString('es-CO', { hour: '2-digit', minute: '2-digit' })}</div><div><h3>{item.patientFirstName} {item.patientLastName}</h3><p>{item.specialty} · {item.location}</p></div><div className="actions"><button onClick={() => void api.close(session.accessToken, item.id, 'COMPLETED')}>Completada</button><button className="secondary" onClick={() => void api.close(session.accessToken, item.id, 'NO_SHOW')}>No asistió</button></div></article>)}</div></section>;
}

function Admin({ session }: { session: Session }) {
  const [data, setData] = useState<AdminDashboard | null>(null); const [users, setUsers] = useState<DirectoryUser[]>([]); const [professionals, setProfessionals] = useState<DirectoryProfessional[]>([]); const [query, setQuery] = useState(''); const [notice, setNotice] = useState('');
  const load = () => Promise.all([api.dashboard(session.accessToken), api.users(session.accessToken, query), api.professionals(session.accessToken)]).then(([dashboard, directory, pros]) => { setData(dashboard); setUsers(directory.items); setProfessionals(pros); }).catch(error => setNotice(error.message));
  useEffect(() => { void load(); }, []);
  return <section className="page-section"><div className="section-title"><div><p className="eyebrow">CENTRO DE OPERACIONES</p><h2>Panorama administrativo</h2></div><button onClick={() => void load()}>Actualizar datos</button></div>{notice && <p className="message">{notice}</p>}<div className="metric-row admin-metrics"><article><strong>{data?.activeUsers ?? '—'}</strong><span>Usuarios activos</span></article><article><strong>{data?.activeProfessionals ?? '—'}</strong><span>Profesionales activos</span></article><article><strong>{data?.pendingRequests ?? '—'}</strong><span>Solicitudes pendientes</span></article></div><div className="analytics"><article className="chart-card"><h3>Citas por estado</h3>{data?.appointmentsByStatus.map(item => <div className="bar" key={item.status}><span>{item.status}</span><i style={{ width: `${Math.min(100, item.total * 20)}%` }} /><b>{item.total}</b></div>) || <p className="muted">Sin actividad aún.</p>}</article><article className="chart-card"><h3>Actividad por sede</h3>{data?.occupationByLocation.map(item => <div className="bar" key={item.name}><span>{item.name}</span><i style={{ width: `${Math.min(100, item.total * 20)}%` }} /><b>{item.total}</b></div>)}</article></div><div className="directory"><div className="section-title"><h3>Usuarios</h3><form onSubmit={event => { event.preventDefault(); void load(); }}><input aria-label="Buscar usuario" placeholder="Buscar por nombre o correo" value={query} onChange={event => setQuery(event.target.value)} /><button>Buscar</button></form></div>{users.map(user => <article className="directory-row" key={user.id}><div className="avatar">{user.firstName[0]}{user.lastName[0]}</div><div><strong>{user.firstName} {user.lastName}</strong><span>{user.email} · {user.roles}</span></div><span className={user.active ? 'pill on' : 'pill'}>{user.active ? 'Activo' : 'Inactivo'}</span><button className="secondary" onClick={() => void api.userActive(session.accessToken, user.id, !user.active).then(load)}>{user.active ? 'Desactivar' : 'Activar'}</button></article>)}</div><div className="directory"><h3>Profesionales</h3>{professionals.map(pro => <article className="directory-row" key={pro.id}><div className="avatar">{pro.firstName[0]}{pro.lastName[0]}</div><div><strong>{pro.firstName} {pro.lastName}</strong><span>{pro.specialties || 'Sin especialidad'} · {pro.locations || 'Sin sede'}</span></div><span className={pro.active ? 'pill on' : 'pill'}>{pro.active ? 'Activo' : 'Inactivo'}</span><button className="secondary" onClick={() => void api.professionalActive(session.accessToken, pro.id, !pro.active).then(load)}>{pro.active ? 'Desactivar' : 'Activar'}</button></article>)}</div></section>;
}

function App() {
  const [session, setSession] = useState<Session | null>(null); const [view, setView] = useState('home'); const [expired, setExpired] = useState(false); const sessionRef = useRef<Session | null>(null);
  useEffect(() => { sessionRef.current = session; }, [session]);
  useEffect(() => {
    if (!session) return;
    let lastActivity = Date.now(); let lastServerTouch = lastActivity; let finished = false;
    const finish = (timedOut: boolean) => { if (finished) return; finished = true; const current = sessionRef.current; if (current) void api.logout(current.accessToken).catch(() => undefined); setExpired(timedOut); setSession(null); };
    const activity = () => { const now = Date.now(); lastActivity = now; const current = sessionRef.current; if (current && now - lastServerTouch >= SERVER_TOUCH_INTERVAL_MS) { lastServerTouch = now; void api.refresh(current.refreshToken).then(next => { sessionRef.current = next; setSession(next); }).catch(() => finish(true)); } };
    const check = () => { if (Date.now() - lastActivity >= IDLE_TIMEOUT_MS) finish(true); };
    const events: Array<keyof WindowEventMap> = ['pointerdown', 'keydown', 'touchstart', 'scroll'];
    events.forEach(event => window.addEventListener(event, activity, { passive: true }));
    document.addEventListener('visibilitychange', activity); const timer = window.setInterval(check, 1000);
    return () => { events.forEach(event => window.removeEventListener(event, activity)); document.removeEventListener('visibilitychange', activity); window.clearInterval(timer); };
  }, [session]);
  if (!session) return <Access expired={expired} onSession={next => { setExpired(false); setSession(next); }} />;
  const role = session.user.roles.includes('ADMIN') ? 'ADMIN' : session.user.roles.includes('PROFESSIONAL') ? 'PROFESSIONAL' : 'USER';
  const content = role === 'ADMIN' ? <Admin session={session} /> : role === 'PROFESSIONAL' ? <Professional session={session} /> : view === 'appointments' ? <MyAppointments session={session} /> : <Booking session={session} />;
  return <main className="app-shell"><aside><div className="brand"><span>✦</span>Agenda Salud</div><nav>{role === 'USER' && <><button className={view === 'home' ? 'active' : ''} onClick={() => setView('home')}>Nueva cita</button><button className={view === 'appointments' ? 'active' : ''} onClick={() => setView('appointments')}>Mis citas</button></>}<button className="nav-muted" onClick={() => void api.logout(session.accessToken).finally(() => setSession(null))}>Cerrar sesión</button></nav></aside><div className="workspace"><header><div><p className="eyebrow">{role}</p><h1>Hola, {session.user.firstName}</h1></div><div className="profile-chip"><span>{session.user.firstName[0]}{session.user.lastName[0]}</span>{role}</div></header>{content}</div></main>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
